apiVersion: v1
kind: Service
metadata:
  name: resortslite-service
  namespace: resortslite
  labels:
    app: resortslite
spec:
  type: ClusterIP
  selector:
    app: resortslite
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
